project:
  type: website
  output-dir: docs

website:
  title: "Barcelona City Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: maps/L5Y_polar_map.html
        text: AQ_polar_plots
      - href: maps/osm_cycle_paths.html
        text: Cycle network
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



